### ISSUE TITLE
FLAC file is corrupted when embedding the cover image

### ISSUE THREAD

**Issue by DPiquero2015** [TeamMemeTeme2410/picard#10]
http://tickets.musicbrainz.org/browse/PICARD-787

https://musicbrainz.org/release/0018b304-f497-4807-8f4a-043dac4e86f6

This is the release that matches for the track.

https://www.dropbox.com/s/enlsi00hq7hxtzu/01%20%E2%98%85.flac?dl=0

This is the link to the track since (over 10MB limit, if it's not available my slow dialuplike is still uploading it).

Options are:

```
embed the image
only the front image is embedded
there's a rename of the file
```

Picard, given these options, crashes and corrupts the file.

flac -d filename

The above command confirms that decoding is impossible but moments before it was.

D: 20:05:16 Skipping cover art provider Cover Art Archive ...
D: 20:05:16 Trying cover art provider Amazon ...
D: 20:05:16 Found ASIN relation : amazon.co.jp B0189JGNSQ
D: 20:05:16 Queing CoverArtImage(url=u'http://ec1.images-amazon.com/images/P/B0189JGNSQ.09.LZZZZZZZ.jpg') for download
D: 20:05:16 Queing CoverArtImage(url=u'http://ec1.images-amazon.com/images/P/B0189JGNSQ.09.MZZZZZZZ.jpg') for download
D: 20:05:16 Downloading CoverArtImage(url=u'http://ec1.images-amazon.com/images/P/B0189JGNSQ.09.LZZZZZZZ.jpg')
D: 20:05:16 Last request to ('ec1.images-amazon.com', 80) was 1000 ms ago, starting another one
D: 20:05:16 GET http://ec1.images-amazon.com/images/P/B0189JGNSQ.09.LZZZZZZZ.jpg
D: 20:05:20 Received reply for http://ec1.images-amazon.com/images/P/B0189JGNSQ.09.LZZZZZZZ.jpg: HTTP 200 (OK) (CACHED)
D: 20:05:20 Saving image data e55c582661de47fe1d9b6f7b71edbc1b to '/tmp/picardTMfsJy.jpg'
D: 20:05:20 Cover art image downloaded: CoverArtImage(url=u'http://ec1.images-amazon.com/images/P/B0189JGNSQ.09.LZZZZZZZ.jpg') [w=500 h=500 mime=image/jpeg ext=.jpg datalen=13918 file=/tmp/picardTMfsJy.jpg]
D: 20:05:20 Moving <File u'01 \u2605.flac'> from <Cluster u'Unmatched Files'> to <Track d85c7c30-d49c-4b06-aa47-d255769db322 u'\u2605'>
D: 20:05:20 Album 0018b304-f497-4807-8f4a-043dac4e86f6 loaded: David Bowie - ★
D: 20:05:38 Updating file <File u'01 \u2605.flac'>

This is the partial log (picard -d output), the logging and picard hangs on the last line.

**Comment by emhazen** [comment]
Assigned
