### ISSUE TITLE
Default size of Options window cuts off category labels

### ISSUE THREAD

**Issue by Kexus** [TeamMemeTeme2410/picard#12]
http://tickets.musicbrainz.org/browse/PICARD-846

**Comment by Kexus** [comment]
http://tickets.musicbrainz.org/browse/PICARD-408 older issue for the same problem

**Comment by Kexus** [comment]
Found in `ui/options.ui` lines 8 and 9, which controls `picard/ui/ui_options.py` line 16

**Comment by elarochelle2013** [comment]
picard < ui < ui_options.py

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(485, 398)`

**Comment by elarochelle2013** [comment]
//home/mint/.config/musicbrainz/picard.ini

**Comment by Kexus** [comment]
Expected Impact: options.ui -> ui_options.py
Actual Impact: options.ui, ui_options.py, (picard.ini)

**Comment by Kexus** [comment]
Actual Actual Impact: options.ui, ui_options.py, picard.ini, dialogue.py
