### ISSUE TITLE
Delete additional files when moving

### ISSUE THREAD

**Issue by emhazen** [TeamMemeTeme2410/picard#2]
http://tickets.musicbrainz.org/browse/PICARD-776

"Similar to the ability to move additional files, the ability to delete these files would be very useful. I use embedded artwork and get rid of everything else before tagging (I usually just search for all the extensions I know of and delete them all at once) but it's getting to be a little troublesome because I forget some of them and then the delete empty directories doesn't work. Not the biggest issue as I usually just delete the folder later anyway..."

**Comment by cheath2013** [comment]
Config option can be added under line 67 of renaming.py and then function will be defined under line 373 of file.py in order to reuse the remove function.

**Comment by cheath2013** [comment]
Option "Delete file type" added. Code used combines already written code to find file types and to remove files. Currently force-closes Picard on execution.

**Comment by cheath2013** [comment]
Expected impact - renaming.py, file.py
