### ISSUE TITLE
 Warn people who try to load very large amounts of files

### ISSUE THREAD

**Issue by emhazen** [TeamMemeTeme2410/picard#4]
http://tickets.musicbrainz.org/browse/PICARD-840

"Fairly often we get messages from users like "I loaded 50k files on Picard and it's going very slowly". We should have some sort of alert for these cases, possibly warn when someone tries to load more than 5k or 10k files in one go and ask "Are you sure you want to load so many files? Picard might run very slowly" or whatnot."

**Comment by emhazen** [comment]
Found in `picard/tagger.py` line 342

Expected impact: `add_files()` and `tagger.files`

**Comment by emhazen** [comment]
You can find the number of files being uploaded in `add_files` by calling `len(new_files)`.

The API for message boxes in QtGUI can be found [here](http://pyqt.sourceforge.net/Docs/PyQt4/qmessagebox.html)

**Comment by emhazen** [comment]
Message box is functioning for a preset maximum. Next step is to allow users to define max file

**Comment by DPiquero2015** [comment]
UI configuration has been added that allows for a threshold on the number of files Picard can take without complaint. The value box has a hard maximum set to 100,000,000 with a default value of 5,000 files.

In the options menu, the threshold can be set under the 'General' category in 'Importing'

`Picard.ini` stores the user threshold created in `options_general.ui` and `options/general.py`
