### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Kexus** [TeamMemeTeme2410/picard#5]
Setting Up Picard

Python 2.7.12

sudo apt-get remove python

sudo apt-get install build-essential checkinstall
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

cd /usr/src
sudo wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
sudo tar xzf Python-2.7.12.tgz

cd Python-2.7.12
sudo ./configure
sudo make altinstall

sudo apt-get install python-pip
sudo apt-get install python-dev
sudo apt-get install python-setuptools
sudo apt-get install python-qt4
sudo apt-get install python-libdiscid

sudo pip install mutagen
sudo pip install discid

Git

sudo apt-get install git

// go where you want the git repo to

git clone https://github.com/TeamMemeTeme2410/picardgit
cd picard
git checkout edit-readme
git pull

Picard

python setup.py build_ext -i
python setup.py build_locales -i

Running Picard

python tagger.py

Sending Changes

git commit -am "Message Description"
git push origin edit-readme

// cli will ask for your git username and password

That should be everything, if anyone runs into issues, ask around

Also, one thing to note about VirtualBox, if you shut down the os like you would your computer, then you lose all your shit
To safely save your stuff and shut down correctly, hit 'RCtrl + Q' and select 'Save the machine state'

**Comment by emhazen** [comment]
Would you move this to the wiki? Thanks
