### ISSUE TITLE
Handle duplicate files

### ISSUE THREAD

**Issue by emhazen** [TeamMemeTeme2410/picard#9]
http://tickets.musicbrainz.org/browse/PICARD-311

"
I do have lots of files with doublettes.

I want to have from every song only one file.

With Picard i can identify and sort to releases.

But i dont care about releases, i care about songs.

Wouldnt it be great if Picard would remove all soundfiles which are available on the hard disc more often then one time?

Picard could check for the quality of the identical songs and keep the one with the best quality.

Picard could also check if the kept MP3 file is valid."

**Comment by Kexus** [comment]
Additional details here http://bugs.musicbrainz.org/ticket/3210

**Comment by Kexus** [comment]
`tagger.py` 335-345, `file.py`

**Comment by Kexus** [comment]
Expected Impact: file.py
